# Generated by Django 4.0.4 on 2022-05-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zawody',
            new_name='Competition',
        ),
        migrations.RenameModel(
            old_name='Zawodnik',
            new_name='Player',
        ),
    ]
